# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\1\Desktop\kurs\application\ui\queries.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 90, 931, 581))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.table.verticalHeader().setVisible(False)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 0, 931, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.executeButton = QtWidgets.QPushButton(self.centralwidget)
        self.executeButton.setGeometry(QtCore.QRect(670, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.executeButton.setFont(font)
        self.executeButton.setObjectName("executeButton")
        self.excelButton = QtWidgets.QPushButton(self.centralwidget)
        self.excelButton.setGeometry(QtCore.QRect(810, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.excelButton.setFont(font)
        self.excelButton.setObjectName("excelButton")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(10, 40, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(340, 40, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Запросы"))
        self.executeButton.setText(_translate("MainWindow", "Выполнить"))
        self.excelButton.setText(_translate("MainWindow", "Excel"))
